const products = [
  {
    id: 1,
    name: "Apple",
    category: "Fruit",
    description: "Г/Ц Блинчики с мясом вес, Россия ",
    price: 89,
    rating: 5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-1.png",
    country: "Uzb",
  },
  {
    id: 2,
    name: "Banana",
    category: "Fruit",
    description:
      "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    price: 71,
    rating: 5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 3,
    name: "Bread",
    category: "Bakery",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан....",
    price: 88,
    rating: 5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 4,
    name: "Broccoli",
    category: "Vegetable",
    description:
      "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    price: 94,
    rating: 4.5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-4.png",
    img1: "../assets/images/Home/home-card-images/img-1.png",
    img2: "../assets/images/Home/home-card-images/img-2.png",
    img3: "../assets/images/Home/home-card-images/img-3.png",
    img4: "../assets/images/Home/home-card-images/img-1.png",
  },
  {
    id: 5,
    name: "Carrot",
    category: "Vegetable",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 82,
    rating: 5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-1.png",
  },
  {
    id: 6,
    name: "Cheese",
    category: "Dairy",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 91,
    rating: 3.5,
    discount: 50,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 7,
    name: "Chicken",
    category: "Meat",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 68,
    rating: 3.5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 8,
    name: "Chocolate",
    category: "Dessert",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 61,
    rating: 4.5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-4.png",
  },
  {
    id: 9,
    name: "Coffee",
    category: "Dessert",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 98,
    rating: 5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-1.png",
  },
  {
    id: 10,
    name: "Egg",
    category: "Dairy",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 79,
    rating: 4.5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 11,
    name: "Fish",
    category: "Meat",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 89,
    rating: 3.5,
    discount: 50,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 12,
    name: "Grapes",
    category: "Fruit",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 61,
    rating: 4,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-4.png",
  },
  {
    id: 13,
    name: "Hamburger",
    category: "Fast food",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 87,
    rating: 5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-1.png",
  },
  {
    id: 14,
    name: "Hot dog",
    category: "Fast food",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 84,
    rating: 4.5,
    discount: 50,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 15,
    name: "Ice cream",
    category: "Dessert",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 68,
    rating: 4.5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 16,
    name: "Lemon",
    category: "Fruit",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 74,
    rating: 3.5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-4.png",
  },
  {
    id: 17,
    name: "Eggs",
    category: "Dairy",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 70,
    rating: 4.5,
    discount: 50,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 18,
    name: "Honey",
    category: "Dairy",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 87,
    rating: 4,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 19,
    name: "Ice Cream",
    category: "Dessert",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 83,
    rating: 4.5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-4.png",
  },
  {
    id: 20,
    name: "Jelly",
    category: "Fruit",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 76,
    rating: 5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 21,
    name: "Ketchup",
    category: "Dairy",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 77,
    rating: 5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 22,
    name: "Mango",
    category: "Fruit",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 80,
    rating: 5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-4.png",
  },
  {
    id: 23,
    name: "Noodles",
    category: "Meat",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 93,
    rating: 3.5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 24,
    name: "Oatmeal",
    category: "Breakfast",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 94,
    rating: 4.5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 25,
    name: "Bacon",
    category: "Breakfast",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 71,
    rating: 3.5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-4.png",
  },
  {
    id: 26,
    name: "Pancakes",
    category: "Breakfast",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 63,
    rating: 4,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-1.png",
  },
  {
    id: 27,
    name: "Waffles",
    category: "Breakfast",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 97,
    rating: 4.5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 28,
    name: "Fried Rice",
    category: "Lunch",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 81,
    rating: 4,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 29,
    name: "Spaghetti",
    category: "Lunch",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 96,
    rating: 3,
    discount: 50,
    image: "../assets/images/Home/home-card-images/img-4.png",
  },
  {
    id: 30,
    name: "Pizza",
    category: "Lunch",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 95,
    rating: 4,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 31,
    name: "Grilled Cheese",
    category: "Lunch",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 100,
    rating: 5,
    discount: 50,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 32,
    name: "Steak",
    category: "Dinner",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 63,
    rating: 4.5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-4.png",
  },
  {
    id: 33,
    name: "Salmon",
    category: "Dinner",
    description:
      "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан....",
    price: 82,
    rating: 4.5,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 34,
    name: "Chicken Alfredo",
    category: "Dinner",
    description:
      "Chicken Alfredo is a pasta dish made with chicken, alsjfkdlkasdfhlkjh.",
    price: 94,
    rating: 4,
    discount: 20,
    image: "../assets/images/Home/home-card-images/img-2.png",
  },
  {
    id: 35,
    name: "Lasagna",
    category: "Dinner",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 70,
    rating: 1,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-3.png",
  },
  {
    id: 36,
    name: "Chocolate Chip Cookies",
    category: "Dessert",
    description:
      "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 98,
    rating: 3.5,
    discount: 0,
    image: "../assets/images/Home/home-card-images/img-1.png",
  },
];
